---
kind: pipeline
type: docker
name: Linting

steps:
- name: PyLint
  image: jfloff/alpine-python
  commands:
  - pip3 install -r requirements.txt
  - pip3 install pylint_runner
  - pylint_runner

---
kind: pipeline
type: docker
name: UnitTests

steps:
- name: PyTest
  image: jfloff/alpine-python
  commands:
  - pip3 install -r requirements.txt
  - pip3 install pytest
  - pytest ./tests/

services:
  - name: redis
    image: redis

---
kind: pipeline
type: docker
name: Dry Run

steps:
- name: Junos
  image: jfloff/alpine-python
  commands:
  - apk add libxml2-dev libxslt-dev python3-dev gcc build-base
  - pip3 install nornir

- name: ASAv
  image: jfloff/alpine-python
  commands:
  - apk add libxml2-dev libxslt-dev python3-dev gcc build-base
  - pip3 install nornir
