---
kind: pipeline
type: docker
name: default

steps:
- name: Linting
  image: alpine:3.12.0
  commands:
  - apk update
  - apk add python3 py3-pip build-base python3-dev
  - pip3 install pylint_runner
  - pylint_runner
