---
kind: pipeline
type: docker
name: Linting

steps:
- name: PyLint
  image: jfloff/alpine-python
  commands:
  - pip3 install -r requirements.txt
  - pip3 install pylint_runner
  - pylint_runner

---
kind: pipeline
type: docker
name: Testing

steps:
- name: PyTest
  image: jfloff/alpine-python
  commands:
  - pip3 install -r requirements.txt
  - pip3 install pytest
  - pytest ./tests/

services:
  - name: redis
    image: redis
