version: "3"

networks:
  production:
  
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - production
    command: --requirepass NotaSecurePassword
      
  configpy:
    image: natemellendorf/configpy:standalone
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - "8000:8000"
    networks:
      - production
    environment:
      - RD_ADDR=redis
      - RD_PORT=6379
      - RD_PW=NotaSecurePassword
      #- GITHUB_ORG=_your_github_org_name_ # Optional
      - GITHUB_CLIENT_ID=_your_oauth_client_id_ # Required
      - GITHUB_CLIENT_SECRET=_your_oauth_client_secret_ #Required
    depends_on:
      - redis
